### ISSUE TITLE
Trading session does not work properly in reports section

### ISSUE THREAD

**Issue by alihamas575** [vfremaux/moodle-report_trainingsessions#22]
Thanks a lot for the plugin @vfremaux  However, I have a problem like this. I installed the plugin along with auth_ticket and use_stats. Use_Stats works. Normally, in use stats, the sample student named student2 seems to have spent 5 hours in the relevant course, but when I enter the reports for the traiding session add-on, it shows the time as 0 min.

![image](https://user-images.githubusercontent.com/54097193/107155747-2c53eb80-698b-11eb-8af4-43ca5ffc17b1.png)

![image](https://user-images.githubusercontent.com/54097193/107155759-4261ac00-698b-11eb-85fc-0f32f783c0ee.png)

In the two pictures above, I tried to draw a report for the year 2020, I said 1 how many months of the report date and update, but it showed the times as 0.

The year 2021 did not appear. stop date year in the selector_form.php file
![image](https://user-images.githubusercontent.com/54097193/107155811-8654b100-698b-11eb-8847-8eb5316004de.png)

I changed it to 2021. However, when I tried to get a report from 2021, it started to give an error warning when writing to the database. You can see this in the above error.

**Comment by vfremaux** [comment]
Hi ali

I have updated MOODLE_37 to MOODLE_39 branches to let the "lastyear" follow the current year +1, and the first year to catch the user time creation date of first users in moodle whitch is more performant thant catching a MIN dat in the log table. 

You may update your version from github. Hope it solves the issue.
In case you still have DB issues, please catch the full debug message in debug mode, and we'll see for a quick fix for that

No need paied support transaction at this point. 

cheers
Valery

**Comment by alihamas575** [comment]
My moodle version is 3.8 but I should install 3.9, the previous one failed
when I installed a different version.

Halim ASA
İG Uzmanı -Bilgi İşlem


Development for Moodle by Valery Fremaux <notifications@github.com>, 8 Şub
2021 Pzt, 23:00 tarihinde şunu yazdı:

**Comment by alihamas575** [comment]
I installed the 3.7 work version to have a try. Yes, leap year automatically increases to +1 year.
However, as seen in the picture below, the problem of writing to the database still continues, I say update by checking the error mode, but it still gives an error but does not write a detail. This is what I have explained for student1 user. I choose student1 user, the date is 12 01 2021 for the start and the end date is 07.02.2021 when I press the update, it warns that the database could not be written.
picture 1
![image](https://user-images.githubusercontent.com/54097193/107277165-19ade500-6a65-11eb-9f8b-0e172e3319c3.png)

However, I choose Student 2 user, I think the dates successfully fetch the data just like the image below.
picture 2
![Per participant_1](https://user-images.githubusercontent.com/54097193/107277553-a0fb5880-6a65-11eb-8b6b-301cf2f65a9e.png)
picture 3
![Per participant_2](https://user-images.githubusercontent.com/54097193/107277487-832df380-6a65-11eb-91a2-f4731c338e39.png)

Now I noticed that the area I framed in blue in picture 3 is the status bar, although the web is full, it turns out to be blank when I press the print button. Below, I throw the image as shown on the web as picture 4.
Resim 4
![image](https://user-images.githubusercontent.com/54097193/107277746-eae43e80-6a65-11eb-9e51-4ee286374954.png)


I get back to the same error, database write error ...
As you can see above, it shows some data on January 12, 2021, February 07, 2021. However, when I do the date 08.02.2021 instead of February 07, the database still gives an error to write, and even though debug mode is checked, it does not give an error message. (So when I try to get a report including today, it still gives an error.)
![image](https://user-images.githubusercontent.com/54097193/107278031-4f9f9900-6a66-11eb-9805-e6dce50c8464.png)

The plug-in shows some students' data from the day before. But when I include the current time (the day we live) as the date, all of them fail to write the database.
For Student 1 user, no matter what date I write, it still gives an error to connect to the database.

**Comment by vfremaux** [comment]
You mean you have turned on the debug mode in developer mode, thats'it ? 
please also check in your database if there is a unique index defined on the mdl_block_use_stats_sessions table, involving sessionstart column and other columns. In which case, remove it.

**Comment by alihamas575** [comment]
I am so sory @vfremaux  :(
I opened the debug mode from moodle settings and there is a warning message like the following, when I enter the training session section, it shows this error.
![image](https://user-images.githubusercontent.com/54097193/107336008-aee2c500-6ac9-11eb-8552-a07522f6cb2e.png)

**Comment by vfremaux** [comment]
On your phpmyadmin, you may one of 2 things : 
1. Remove this unique key form table definition
or
2. check if sessionend is part of the key, and add sessionend to the key

there should be very low chance that sessionstart and sessionend make duplicates.

**Comment by alihamas575** [comment]
Thanks a lot phpmyadminde in moodle database
I went into the structure section in the following table: mdl_block_use_stats_session
I edited the following index in the indexes section: mdl_blocusestatsess_useses_uix

When I added sessionendi and hit Go, the problem was resolved.
![indexduzenleme](https://user-images.githubusercontent.com/54097193/107397956-34896380-6b10-11eb-9cd3-330de65938fa.png)

You can turn it off as this issue has been resolved. 
![Per participant_3](https://user-images.githubusercontent.com/54097193/107398306-8cc06580-6b10-11eb-8d25-5fd3bf2067e1.png)
![Per participant_4](https://user-images.githubusercontent.com/54097193/107398315-8fbb5600-6b10-11eb-9720-224c84ca14fe.png)

Now I have a new problem. I will open a separate topic for it. Thank you very much. Good work
