### ISSUE TITLE
Moodle 3.3+ and "PRO" version

### ISSUE THREAD

**Issue by Zell1000** [vfremaux/moodle-report_trainingsessions#6]
Hello,
I tried installing the plugin on moodle 3.3+, but the activity time information is empty, while the 3.20 moodle version works fine.
Will a version of 3.3+ and above be created, or will it not be updated?
Also I sent a mail to know the price and the way to get the "PRO" version but I have not yet received a response ... you could kindly tell me who to contact me for the "PRO" version and know if there will be updates for the version of Moodle higher than 3.2?
Thanks so much,
Best regards,
Tony.

------------------------------------------------

Salve,
ho provato ad installare il plugin su moodle 3.3+, ma le informazioni sul tempo delle attività risultano vuote, mentre con la versione di moodle 3.2+ funziona bene.
Verrà creata una versione per la 3.3+ e oltre, oppure non verrà più aggiornato?
Inoltre avevo mandato una mail per sapere il prezzo e il modo per ottene la versione "PRO" ma non ho ancora ricevuto risposta... potreste gentilmente dirmi a chi rivolgermi per la versione "PRO" e sapere se ci saranno aggiornanti per la versione di moodle superiori alla 3.2?
Grazie mille,
Cordiali saluti,
Tony.

**Comment by vfremaux** [comment]
hi tony, i sent you a mail answer about that with reference to Florence who manages our international distibution

M3.3 will be addressed in a near future while we are going through it in the next months

**Comment by Zell1000** [comment]
Thanks so much. I refer to my superiors.
